### ISSUE TITLE
Arrival timetable

### ISSUE THREAD

**Issue by murki25** [gaudes/ioBroker.fahrplan#125]
**Describe wanted Enhancement !**  
Arrival timetable for stations

**Why should we put effort in it ?**  
Similar to the departure time table arrivals for stations would be helpful so user of visualization may obtain information like "dad is in time / will be late by 20 minutes"

**Additional context**  
hafas-client already implents arrival and departure timetables

**Comment by gaudes** [comment]
Hi @murki25 

can't you use the route-function ?

**Comment by murki25** [comment]
It's the last station on (one) line. I could use the route function from the last stop before that station, but that result will be available only until the train reaches that last station.
-> Planned arrival on station B is 18:00, if using route from A to B will give me e.g. 17:50 A -> 18:02 B (2 min delayed) but this information will be available only up to 17:50 as only future routes are listed.

**Comment by gaudes** [comment]
Reopen

**Comment by gaudes** [comment]
Hi @murki25 

I'm sorry, but I don't have much time at the moment.

I will keep your feature request in backlog. When more users request it, I will integrate your request.

I hope this is ok for you.

Regards, Ralf
