### ISSUE TITLE
"Schweizerische Bundesbahnen" station search not working

### ISSUE THREAD

**Issue by waehli** [gaudes/ioBroker.fahrplan#137]
Everything works fine for Station search Germany or Austria. But for Switzerland, there is a Error displayed in the protocol:
![image](https://user-images.githubusercontent.com/12456149/129534962-5b0952ea-3d13-4a90-8346-95aaaac6c83f.png)
Can this be a problem with the codepage?

**Comment by gaudes** [comment]
Hi @waehli 

I've made an issue at Hafas:

https://github.com/public-transport/hafas-client/issues/245

I'll wait for response and keep you informed.

Regards, Ralf

**Comment by gaudes** [comment]
Hi @waehli ,

one question: Does this request permanently fail ?

Or is it a temporary error and e.g. one hour later it works ?

Regards Ralf

**Comment by gaudes** [comment]
Hey @waehli ,

sorry, but SBB doesn't use HAFAS anymore.

So I have to remove SBB from the adapter.

Regards, Ralf
