### ISSUE TITLE
minor Translation flaw - Platform -> Gleis

### ISSUE THREAD

**Issue by tinoanic** [gaudes/ioBroker.fahrplan#153]
deptt.js line 9: could you please translate 'platform' to 'Gleis' instead of 'Plattform'. This will be the better translation.
Thanks a lot!

**Comment by gaudes** [comment]
Hey @tinoanic ,

this Adapter also gets information about busses, so "Gleis" would be wrong. Therefore I decided to use "Plattform".

Regards, Ralf
