### ISSUE TITLE
Not getting Date/Time out of ioBroker object

### ISSUE THREAD

**Issue by demji1985** [gaudes/ioBroker.fahrplan#167]
Hi,

I am trying to get the "Fahrplan" adapter into a visualization, but when I am trying to import departure or arrival times, it is not giving me any time/date, just plain numbers like "1638532740000".

Why am I not getting the value but some random number (maybe objectID?)

Help and assistance appreciated!

![Unbenannt](https://user-images.githubusercontent.com/85067087/144600797-9873ecc1-d50e-4623-95ab-28711c5832ff.JPG)
![Unbenannt2](https://user-images.githubusercontent.com/85067087/144600799-94898eb5-0d24-411d-9beb-fbf21c3abcbc.JPG)
![Unbenannt3](https://user-images.githubusercontent.com/85067087/144600801-10541009-466b-468c-a35e-dabe22ac3e32.JPG)
![Unbenannt4](https://user-images.githubusercontent.com/85067087/144600802-6e8abd33-4c73-4579-87a7-6e71b0515102.JPG)

**Comment by demji1985** [comment]
No one around?

**Comment by gaudes** [comment]
Hi @demji1985 

this is not a adapter problem, I've found the solution in forum.

You can use for example this:

{fahrplan.0.0.0.0.DeparturePlanned;date(DD.MM.YY - hh:m)}

Regards, Ralf
