### ISSUE TITLE
Depatures Timetables, Filter not work

### ISSUE THREAD

**Issue by CarminKern** [gaudes/ioBroker.fahrplan#175]
**Describe the bug**  
The vehicle Filter of the Depatures Timetables not work correct.

**To Reproduce**  
![image](https://user-images.githubusercontent.com/38145343/149657376-379f95eb-dac3-4bee-8fe5-3ab0e66ce79f.png)

**Expected behavior**  
![image](https://user-images.githubusercontent.com/38145343/149655627-194e7ad8-7e5c-4490-bf82-dcdd176dcc57.png)

**Screenshots & Logfiles**  
^^

**Versions:**  
 - Adapter version: v1.2
 - JS-Controller version: 3.3.22
 - Node version: <node-version> v17.3.1
 - Operating system: Raspbian Lite (NEWEST)

**Additional context**  
If I only specify S-Bahn, then buses will still be displayed to me. If I only specify buses, only buses are displayed.

**Comment by gaudes** [comment]
Hi @CarminKern,

can you please send me the content of the JSON state ?

Thanks, Ralf

**Comment by CarminKern** [comment]
the JSON of "DepartureTimetable3"
`{
  "type": "state",
  "common": {
    "name": "Departure Timetable JSON",
    "type": "string",
    "role": "json",
    "read": true,
    "write": false,
    "desc": "Departure Timetable JSON"
  },
  "native": {},
  "from": "system.adapter.fahrplan.0",
  "user": "system.user.admin",
  "ts": 1642328333689,
  "_id": "fahrplan.0.DepartureTimetable3.JSON",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

the Json of "0" It is a Bus
`{
  "type": "state",
  "common": {
    "name": "Departure JSON",
    "type": "string",
    "role": "json",
    "read": true,
    "write": false,
    "desc": "Departure JSON"
  },
  "native": {},
  "from": "system.adapter.fahrplan.0",
  "user": "system.user.admin",
  "ts": 1643897223062,
  "_id": "fahrplan.0.DepartureTimetable3.0.JSON",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by gaudes** [comment]
Hi @CarminKern 

I mean the state named "JSON". Maybe you have to activate the writing of JSON in the adapter settings.

The state has a string value which contains the data submitted by HAFAS.

**Comment by CarminKern** [comment]
Oh sorry 😅


DepartureTimetable3/JSON
`{"tripId":"1|802592|4|81|4022022","stop":{"type":"stop","id":"682659","name":"Fischbach Bahnhof, Nürnberg","location":{"type":"location","id":"682659","latitude":49.413353,"longitude":11.174904},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false},"station":{"type":"station","id":"8001989","name":"Fischbach(Nürnberg)","location":{"type":"location","id":"8001989","latitude":49.413281,"longitude":11.174149},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false}}},"when":"2022-02-04T23:10:00+01:00","plannedWhen":"2022-02-04T23:10:00+01:00","delay":null,"platform":null,"plannedPlatform":null,"direction":"Langwasser Mitte","provenance":null,"line":{"type":"line","id":"5-vanbus-56","fahrtNr":"45714","name":"Bus 56","public":true,"adminCode":"vanbus","productName":"Bus","mode":"bus","product":"bus","operator":{"type":"operator","id":"nahreisezug","name":"Nahreisezug"}},"remarks":[],"currentTripPosition":{"type":"location","latitude":49.411888,"longitude":11.172342}} `


DepartureTimetable3/0/JSON 
`{"tripId":"1|802592|4|81|4022022","stop":{"type":"stop","id":"682659","name":"Fischbach Bahnhof, Nürnberg","location":{"type":"location","id":"682659","latitude":49.413353,"longitude":11.174904},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false},"station":{"type":"station","id":"8001989","name":"Fischbach(Nürnberg)","location":{"type":"location","id":"8001989","latitude":49.413281,"longitude":11.174149},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false}}},"when":"2022-02-04T23:10:00+01:00","plannedWhen":"2022-02-04T23:10:00+01:00","delay":null,"platform":null,"plannedPlatform":null,"direction":"Langwasser Mitte","provenance":null,"line":{"type":"line","id":"5-vanbus-56","fahrtNr":"45714","name":"Bus 56","public":true,"adminCode":"vanbus","productName":"Bus","mode":"bus","product":"bus","operator":{"type":"operator","id":"nahreisezug","name":"Nahreisezug"}},"remarks":[],"currentTripPosition":{"type":"location","latitude":49.411888,"longitude":11.172342}} `

**Comment by gaudes** [comment]
@CarminKern

Just to confirm: Can you check if the problem is solved with the current version from GitHub ?
I use HAFAS module and made an update last week.
