### ISSUE TITLE
Folder content are not updated

### ISSUE THREAD

**Issue by CarminKern** [gaudes/ioBroker.fahrplan#176]
**Describe the bug**  
The folder conent are not updated.

**To Reproduce**  
![image](https://user-images.githubusercontent.com/38145343/149656413-890c7c8b-d949-4c48-a7be-c60d9e25b8c8.png)

**Expected behavior**  
![image](https://user-images.githubusercontent.com/38145343/149657247-fe177b64-9bc6-47ba-9da7-f4b65a813ec5.png)
![image](https://user-images.githubusercontent.com/38145343/149657275-e3023dc2-7b06-44af-8b9f-ed2b0c29ac2f.png)

**Screenshots & Logfiles**  
^^

**Versions:**  
 - Adapter version: v1.2 (newest)
 - JS-Controller version: 3.3.22 (newest)
 - Node version: 17.3.1 (newest)
 - Operating system: Raspbian (newest)

**Additional context**  
Perhaps it makes sense not to specify the line name (e.g. Departure Fischbach(Nuremberg) - Roth) in the folder content and to create an extra object for it.

**Comment by gaudes** [comment]
Hi @CarminKern ,

thanks, that's right.

The channel description should not contain changing informations. I removed the direction.

Can you test it ?

Please install from Git. Afterwards stop the adapter and remove the complete fahrplan.0 tree from the objects.

Thanks, Ralf

**Comment by CarminKern** [comment]
I have now installed it from Github

Ok, I see they have taken the direction out of the folder content.

![image](https://user-images.githubusercontent.com/38145343/152645026-502d89ef-36a3-4c7b-8408-24e748b3596e.png)

**Comment by gaudes** [comment]
Perfect, I'll close the issue. In the next version this will be integrated.
