### ISSUE TITLE
node-fetch v3 will NOT work!!

### ISSUE THREAD

**Issue by Apollon77** [gaudes/ioBroker.fahrplan#209]
becaus eis ESM only ... you need to stay with v2 from node-fetch!!

Somehow your tests did not triggered an issue so most likely tests do not "include" node-fetch

**Comment by gaudes** [comment]
@Apollon77 : Seems that I don't use node-fetch
Didn't find any "fetch" in files. 
```npx depcheck``` says it also.
I've removed the dependency.

Thanks and kind regards,

Ralf
