### ISSUE TITLE
delay not working

### ISSUE THREAD

**Issue by einfachjannik** [gaudes/ioBroker.fahrplan#226]
Seit 2 Tagen wird mir keine Verspätung mehr angezeigt auch nach einem Neuinstallation nicht.

Woran kann es liegen ?

**Comment by gaudes** [comment]
Hallo,
hast mal auf der Webseite der Bahn geschaut ob da welche angezeigt werden?
Grundsätzlich verwendet der Adapter HAFAS als Schnittstelle, also die "offizielle" Schnittstelle der Bahn.
Ich habe da keine Einflussmöglichkeit.
VG Ralf
