### ISSUE TITLE
Frage zur Darstellung in Vis

### ISSUE THREAD

**Issue by New-three** [gaudes/ioBroker.fahrplan#260]
Erstmal großes Lob zum Adapter.

Vielleicht bin ich hier auch falsch, aber könnt ihr mir ein Beispiel nenen wie ich den Datenpunkt Abfahrtszeit in Vis dargestellt bekomme. Stehe mir da echt auf dem Schlauch.
Ich habe es mit String und Number versucht, doch werden mir hier nur Zahlenkombinationen angezeigt.

**Comment by gaudes** [comment]
Hi @New-three ,

schau mal hier: #167 

VG Ralf
