### ISSUE TITLE
Attention!!! Sentry spammed 180k messages today ... Disabled. please fix!!

### ISSUE THREAD

**Issue by Apollon77** [gaudes/ioBroker.fahrplan#288]
see https://sentry.iobroker.net/organizations/iobroker/issues/6154/?project=105&query=is%3Aunresolved&referrer=issue-stream or catch the error and release new version!

**Comment by gaudes** [comment]
Dear @Apollon77 ,

I've just released a new version which fixes the bug.

PR is open for stable, see here:
https://github.com/ioBroker/ioBroker.repositories/pull/2216

Thanks and regards,
Ralf

**Comment by Apollon77** [comment]
Thank you, merged.

Do you want to inform users to upgrade?
If you like you can add a block like https://github.com/Apollon77/ioBroker.alexa2/blob/master/io-package.json#L5-L13 to you io-package (no need for a new version) ... then you could declare all older versions as blocked. then admin will prevent start of them

In Sentry I would activate again but block all versions from before?
