### ISSUE TITLE
Die S-Bahn Stationen rund um Köln werden nicht mehr erkannt. Der Adapter meldet, dass die IDs nicht bekannt sind. Sind die Stations-IDs geändert worden?

### ISSUE THREAD

**Issue by Kalmar76** [gaudes/ioBroker.fahrplan#289]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by gaudes** [comment]
See #290
