### ISSUE TITLE
wrong place to post

### ISSUE THREAD

**Issue by averlon** [gaudes/ioBroker.fahrplan#319]
I know, I am wrong here.
I am looking for @gaudes, since he/she is listed as well at "bashGroup / node-red-contrib-fritz".
I have started a discussion there but no one seems to be active at that group!?

Is @gaudes still active there or knows others to reactivate?

**Comment by averlon** [comment]
anyone here?

**Comment by gaudes** [comment]
Hello averlon,

long, long time ago :-)

I'm not using node-red anymore.

Regards, Ralf
