### ISSUE TITLE
Abfahrtstafel genauer konfigurieren

### ISSUE THREAD

**Issue by emddummi** [gaudes/ioBroker.fahrplan#363]
**Describe wanted Enhancement !**  
Ich möchte gerne an einer Haltestelle nicht nur die Abfahrten eines bestimmten Verkehrsmittels haben, sondern auch nur einer bestimmten Linie (BUS) und dann noch nur eine Richtung wenn man möchte.

Aktuell sehe ich die nächsten 6 Abfahrten von 3 Linien an einer Haltestelle und dies auch für beide Richtungen die der BUS fährt.

Ich will wirklich nur die sehen die ich nutzen will und ob die alle pünktlich sind oder nicht ;)

Ansonsten vielen Dank für den Adapter, damit können meine Kinder sich schon sehr gut orientieren wann sie losgehen müssen zur Schule ;)

**Comment by gaudes** [comment]
Hallo @emddummi Dann würde ich eher die Routen empfehlen, die sind eigentlich genau dafür gemacht.
