### ISSUE TITLE
Keine Route gefunden, wenn nur ein Verkehrsmittel ausgesucht wird

### ISSUE THREAD

**Issue by techducks** [gaudes/ioBroker.fahrplan#42]
Hallo, 
ich habe eine neue Route erstellt und mir zwei Bahnhöfe rausgesucht. Zwischen diesen beiden Bahnhöfen fährt ein RE ohne umsteigen zu müssen. 
Wenn ich in der Route bei der Verkehrsmittelauswahl nur "RE,IR" auswähle, dann kommt folgende Meldung:
`
fahrplan.0 | 2020-12-28 13:20:33.947 | error | (6568) No journeys found for route 0 (HAFAS-Error H890)
`
Ich hab den Fahrplan abgeglichen und kann bestätigen, dass ein Zug (auch zu dem Zeitpunkt) zwischen diesen beiden Punkten fährt. 

Gruß

**Comment by gaudes** [comment]
Hi @techducks 

kannst Du mir bitte einen Screenshot der Konfig anhängen ?
Dann kann ich es nachvollziehen.

Danke.

**Comment by techducks** [comment]
![1](https://user-images.githubusercontent.com/63047974/103218095-6bb60380-491a-11eb-8d59-5e93e96523f8.png)

![1](https://user-images.githubusercontent.com/63047974/103218232-c9e2e680-491a-11eb-9519-993d849f9014.png)

Hier ist ein Screenshot der Routen-Config :) 

Ich habe übrigens noch ein paar Fehler (und Verbesserungsvorschläge) zu berichten. Soll ich für alles in Issue aufmachen oder im Forum sschreiben?

**Comment by gaudes** [comment]
Habs grad nachvollzogen.

Die Auswahl der Verkehrsmittel entspricht auf der Webseite der Bahn der folgenden:

![image](https://user-images.githubusercontent.com/34286177/103219100-13343580-491d-11eb-89a1-cdb1beb1d769.png)

Da kommt dann auch der H890 bei der Bahn-Webseite direkt. Wenn man bei der Bahn "NV" noch auswählt, bzw. im Adapter "RB" noch dazunimmt, dann gehts.

Ich sehe aber nur einen "RE" aktuell, und der ist vom Betreiber "National Express". Eventuell wird der zwar als "RE" benannt, aber intern doch als RB klassifiziert.

Somit ist es aber auf der Webseite der Bahn bei Auswahl der gleichen Verkehrsmittel exakt das gleiche. Somit kann ich da im Adapter leider auch nicht viel anderes tun.

Passt das so ?
