### ISSUE TITLE
Add Line/Route Number to HTML Journey Report

### ISSUE THREAD

**Issue by flyboy70** [gaudes/ioBroker.fahrplan#427]
I love this Adapter - Thank you !
I am outputting this via IOBroker to Jarvis HTML Widget, and when i select ALL DEPARTURES from our town, there is NO Bus Line Number visible.

Current Columns are:
TIME / DIRECTION / PLATFORM / DELAY / TYPE

![JSON](https://github.com/user-attachments/assets/64f8e9a3-b6a7-4cda-8f7e-ff06a263247c)
![JSON1](https://github.com/user-attachments/assets/4e6d0cb5-f7f2-4e79-a60d-4d95b41801b0)

I see in the JSON File Results that all information is available, but I am not good enough to extract the columns from JSON to the JSON Widget.

Or provide instructions how we can extract the Information we need from the JSON file in the documentation. 

Ideal would be:
Bus Line Number / Scheduled Arrival Time / Delay / Direction / 

Thanks !

**Comment by gaudes** [comment]
Hello @flyboy70 

There are so different preferences for the output. But all fields are direct object in ioBroker.

I don't no Jarvis, but in normal VIS it is possible to reference ioBroker objects in HTML code. So you could create a table as you prefer.

Maybe you can ask in the ioBroker Forum or someone who knows Jarvis ?

Kind regards, Ralf
