### ISSUE TITLE
Objekte klappen bei jeder aktualisierung auf

### ISSUE THREAD

**Issue by bertl83** [gaudes/ioBroker.fahrplan#50]
Im Reiter Objekte klappt der komplette Baum des Fahrplans bei jeder aktualisierung auf.
Ich denke das sollte so nicht sein?

**Comment by gaudes** [comment]
Hi,

da kann ich im Adapter nichts machen, da ich darauf keinen Einfluss habe.

Dein Webbrowser "abonniert" quasi die Objekte, welche Du dir anzeigen lässt, also aufklappst.

Versuch doch mal den Browser-Cache (inkl. Cookies) komplett zu löschen bzw. einen anderen Browser zu verwenden.

Klappt es dann ?

VG Ralf

**Comment by gaudes** [comment]
@bertl83 Ist das Problem gelöst durch das Löschen des Browser-Caches ?

**Comment by bertl83** [comment]
oh, sorry. Besser schon, weg nicht, aber man gewöhnt sich dran :) Mittlerweile ist mir das auch schon bei anderen Adaptern aufgefallen. Mag also durchaus auch an meinen Browser liegen.

**Comment by gaudes** [comment]
@bertl83 : Hast den Cache vom Browser mal gelöscht ?

**Comment by bertl83** [comment]
Ja, mit allen möglichen anderen auch.
Aber wie gesagt, passiert das ned nur beim Fahrplan sondern auch bei anderen Adaptern bei mir.
Kannst zumachen das Ticket.

⁣Gesendet von meinem Huawei ​
