### ISSUE TITLE
Feature Request - Farbformatierung der HTML Ansicht

### ISSUE THREAD

**Issue by mark77-DE** [gaudes/ioBroker.fahrplan#76]
Moin,

es wäre super, wenn man für die HTML Ansicht die Farebn formatieren könnte. Ich nutze in der VIS einen blauen Hintergrund, wo das grün sehr schlecht zu lesen ist.

Ansonsten, Danke für den Adapter und weiter so!

Gruß,
Mark

**Comment by gaudes** [comment]
Moin,

ich habe es gerade eingebaut:

Musst von Git installieren, die Versionsnummer ist erstmal die gleiche geblieben.

Bitte mal testen und eine Rückmeldung geben.

VG Ralf

**Comment by mark77-DE** [comment]
Moin,

läuft!

Danke!

Gruß,
Mark

**Comment by gaudes** [comment]
Hi,

da steckt folgende dahinter:

Wenn ich die Info habe dass der Zug wirklich pünktlich ist, dann wirds grün.
Wenn es keine Info gibt, also nur die geplante Abfahrtszeit, dann bleibt es in der Standardfarbe.

Also:
grün = bestätigt pünktlich
Standardfarbe = Keine Info
rot = bestätigt verspätet

VG Ralf

**Comment by mark77-DE** [comment]
Alles klar! Danke für deine Rückmeldung!
