### ISSUE TITLE
Symbole und Buslinie/Zugnummer

### ISSUE THREAD

**Issue by juergenS09** [gaudes/ioBroker.fahrplan#88]
Hi, 
Ich bin recht neu, was iobroker betrifft und habe den Fahrplan nun in Benutzung. Dazu habe ich eine Frage, siehe auch Betreff.
Ist es möglich, die jeweiligen Buslinien/Zugnummern ebenfalls abzubilden in der vis?
Ich nutze fahrplan Version 1.0.7
In der vis stelle ich fahrplan.0.0.HTML dar.
![20210421_061505](https://user-images.githubusercontent.com/82924404/115496014-199e4280-a269-11eb-824c-315867c433ee.jpg)
Leider sehe ich bei Plattform den Eintrag "null", das ist eine Busverbindung.

Vielen Dank und Grüße 
Jürgen

**Comment by gaudes** [comment]
Hi @juergenS09 ,

bei den HTML-Ansichten gibt es leider gefühlt 100 unterschiedliche Meinungen.

Ich habe versucht, die wichtigsten abzubilden.

Du kannst Dir die Tabelle aber auch selbst zusammenbauen, ganz nach persönlichem Wunsch.

Verwende hierzu einfach eine HTML-Tabelle. An den Stellen, an denen Daten stehen sollen musst Du dann einfach zum Beispiel folgendes eintragen:

{fahrplan.0.0.0.Arrival}

Reicht Dir das ?

VG Ralf

**Comment by juergenS09** [comment]
Hi Ralf,
Danke Dir für die Info.
Da muss ich mich dann mal einlesen, wie man es umsetzen kann, eine Tabelle mit eigenen Datenpunkten zu füllen. Ist noch komplettes Neuland für mich.
Eine andere Frage hab ich noch, als Beispiel:
Ich fahre mit Bus zum Hbf, von dort nehm ich einen Zug.
Gibt es die Möglichkeit, mir nur Züge anzeigen zu lassen, die abfahren, wenn der Bus den Bahnhof erreicht hat?
Ich glaube, das Du das mal umgesetzt hattest, wenn ich mir den Trend anschaue:
https://forum.iobroker.net/topic/37043/test-adapter-fahrplan-v0-2-x/9
Ich finde nur leider den entsprechenden Eintrag nicht.

Viele Grüße 

Jürgen

**Comment by gaudes** [comment]
Hi,

den Eintrag musst Du an der beschriebenen Stelle selbst erstellen.

Ich dachte damals, dass es ein Sonderwunsch ist und habe es nicht in die GUI eingebaut.

Darf ich fragen warum Du dir keine Route von A nach B via HBF einrichtest ?

Dann hättest ja das gleiche Ergebnis, aber musst nicht selbst schauen / rechnen.

VG Ralf

**Comment by juergenS09** [comment]
Hi Ralf,ich nutze Routen, 3 Verbindungen.Wenn ich die default html in vis nutze, zeigt er mir meine Verbindung von A-B mit gleicher Abfahrtszeit, wie auch B-C.Sprich, meine Busverbindung A-B startet um 07:14 Uhr, gleichzeitig aber auch die Zugverbindung B-C, obwohl der Bus noch nicht am Bahnhof ist. Da fände ich ein Delay praktisch, da der Bus ca 20 min zum Bahnhof benötigt. Anbei ein Screenshot, links die Busverbindung, rechts Zugverbindung.Nochwas: wenn ich mir selber eine Tabelle baue und Datenpunkte wie Arrival nutze, wird mir die Zeit als Unix Timestamp angezeigt.Hast Du eine Idee, wie ich das in eine "normale" Zeit umschreiben kann?Viele GrüßeJürgenAm 25.04.2021 21:07 schrieb gaudes ***@***.***>:

Hi,

den Eintrag musst Du an der beschriebenen Stelle selbst erstellen.

Ich dachte damals, dass es ein Sonderwunsch ist und habe es nicht in die GUI eingebaut.

Darf ich fragen warum Du dir keine Route von A nach B via HBF einrichtest ?

Dann hättest ja das gleiche Ergebnis, aber musst nicht selbst schauen / rechnen.

VG Ralf



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Am 25.04.2021 21:07 schrieb gaudes ***@***.***>:

Hi,

den Eintrag musst Du an der beschriebenen Stelle selbst erstellen.

Ich dachte damals, dass es ein Sonderwunsch ist und habe es nicht in die GUI eingebaut.

Darf ich fragen warum Du dir keine Route von A nach B via HBF einrichtest ?

Dann hättest ja das gleiche Ergebnis, aber musst nicht selbst schauen / rechnen.

VG Ralf



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Am 25.04.2021 21:07 schrieb gaudes ***@***.***>:

Hi,

den Eintrag musst Du an der beschriebenen Stelle selbst erstellen.

Ich dachte damals, dass es ein Sonderwunsch ist und habe es nicht in die GUI eingebaut.

Darf ich fragen warum Du dir keine Route von A nach B via HBF einrichtest ?

Dann hättest ja das gleiche Ergebnis, aber musst nicht selbst schauen / rechnen.

VG Ralf



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Am 25.04.2021 21:07 schrieb gaudes ***@***.***>:

Hi,

den Eintrag musst Du an der beschriebenen Stelle selbst erstellen.

Ich dachte damals, dass es ein Sonderwunsch ist und habe es nicht in die GUI eingebaut.

Darf ich fragen warum Du dir keine Route von A nach B via HBF einrichtest ?

Dann hättest ja das gleiche Ergebnis, aber musst nicht selbst schauen / rechnen.

VG Ralf



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Am 25.04.2021 21:07 schrieb gaudes ***@***.***>:

Hi,

den Eintrag musst Du an der beschriebenen Stelle selbst erstellen.

Ich dachte damals, dass es ein Sonderwunsch ist und habe es nicht in die GUI eingebaut.

Darf ich fragen warum Du dir keine Route von A nach B via HBF einrichtest ?

Dann hättest ja das gleiche Ergebnis, aber musst nicht selbst schauen / rechnen.

VG Ralf



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Am 25.04.2021 21:07 schrieb gaudes ***@***.***>:

Hi,

den Eintrag musst Du an der beschriebenen Stelle selbst erstellen.

Ich dachte damals, dass es ein Sonderwunsch ist und habe es nicht in die GUI eingebaut.

Darf ich fragen warum Du dir keine Route von A nach B via HBF einrichtest ?

Dann hättest ja das gleiche Ergebnis, aber musst nicht selbst schauen / rechnen.

VG Ralf



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Am 25.04.2021 21:07 schrieb gaudes ***@***.***>:

Hi,

den Eintrag musst Du an der beschriebenen Stelle selbst erstellen.

Ich dachte damals, dass es ein Sonderwunsch ist und habe es nicht in die GUI eingebaut.

Darf ich fragen warum Du dir keine Route von A nach B via HBF einrichtest ?

Dann hättest ja das gleiche Ergebnis, aber musst nicht selbst schauen / rechnen.

VG Ralf

**Comment by gaudes** [comment]
Hi,

warum nimmst Du als Route nicht einfach A-C ?

Zur Zeit: Musst mal im Forum suchen, es gibt eine Möglichkeit die Uhrzeit innerhalb der geschweiften Klammern mittels JavaScript zu formatieren.

VG Ralf

**Comment by juergenS09** [comment]
Hi Ralf,
Ich konnte A-C nicht nehmen, da ich in B umsteigen muss. Die vorgefertigte Html-Ansicht zeigt mir leider nicht, an welchem Gleis ich wann umsteigen muss. Oder ich hab es nicht gesehen. 
Ich arrangiere mich mit dem was vorhanden ist und bastel mir den Rest drumherum.
Ich wünsche Dir einen schönen Sonntag.

Grüße 

Jürgen

**Comment by gaudes** [comment]
Hi @juergenS09 

ich habe gerade einen "Zeit-Offset" für Routen und Abfahrtstafeln integriert.

Bitte mal die aktuelle Version über die Katze von Github installieren und ausprobieren.

Bitte gib mir eine Rückmeldung ob es soweit funktioniert.

VG Ralf

**Comment by gaudes** [comment]
@juergenS09 Hi,

bist schon zu den weiteren Tests gekommen? Klappt alles?

VG Ralf

**Comment by juergenS09** [comment]
Guten Morgen Ralf,
ich habe mir das Ganze nochmal angesehen.
Zuerst den alten Adapter entfernt und dann nach Neustart Dein Release über das KAtzensymbol neu installiert.
Ich habe nur 2 Routen zum Test genutzt, sehe aber in der vis kein Delay.
Anbei Bilder, wie ich es konfiguriert habe:
![grafik](https://user-images.githubusercontent.com/82924404/119215062-92442900-bacb-11eb-93ad-3765b7f5ca91.png)

in der vis schaut es dann so aus:

![grafik](https://user-images.githubusercontent.com/82924404/119215114-f23acf80-bacb-11eb-961e-ae384d206c77.png)

Nicht über den Versatz zwischen Überschrift und Einträgen wundern, mein Laptop stellt die vis anders dar als mein Tablet.
Für die Darstellung der beiden Tabellen nutze ich:
{fahrplan.0.0.HTML}
{fahrplan.0.1.HTML}
Ich sehe keinen Delay zwischen Ankunft an Ziel und Abfahrt.
Muss ich hier etwas völlig anderes einstellen?
Ich weiss echt nicht, wie ich das darstellen könnte. Mache ich etwas grundlegend falsch oder habe ich irgendwo einen Denkfehler?
Für mich sieht es so aus, als wenn für jede Route die Abfahrtszeit aus der Systemzeit generiert wird und von daher kein Delay entstehen kann. Es wird ja immer von der "Jetzt"-Zeit ausgegangen, unabhängig dessen, ob es eine eingetragene Verzögerung gibt.
Was mich ebenfalls wundert ist folgendes im system.adapter.fahrplan:
![grafik](https://user-images.githubusercontent.com/82924404/119215285-08955b00-bacd-11eb-8c12-a04de721cbf6.png)

Müsste hier nichts eingetragen sein?


Grüße

Jürgen

**Comment by gaudes** [comment]
Hi @juergenS09 

das sieht wirklich seltsam aus. Bist Du zufällig in Discord aktiv ? Dann können wir es mal gemeinsam anschauen.

VG Ralf

**Comment by juergenS09** [comment]
Guten Morgen Ralf,
nein, Discord habe/nutze ich nicht.
Grüße
Jürgen

**Comment by gaudes** [comment]
Hi @juergenS09 

hatte bei den Routen noch einen Bug.

Kannst es nochmal über die Katze updaten und testen ?

Danke und Grüße

Ralf

**Comment by juergenS09** [comment]
Guten Morgen Ralf,
yippie, das sieht super aus, klasse.
Vorgehensweise:
Instanz gelöscht, Adapter deinstalliert, Reboot, danach über "Katze" Adapter neu installiert und Instanz zugefügt.
Einstellungen wie folgt vorgenommen:
![grafik](https://user-images.githubusercontent.com/82924404/120270219-8285cb00-c2a9-11eb-8956-6bb5e44062e2.png)

Anzeige in vis sieht nun so aus:
![grafik](https://user-images.githubusercontent.com/82924404/120270038-32a70400-c2a9-11eb-8ae8-8e6a780ac463.png)
Delay ist bei den Abfahrten deutlich sichtbar, auch zwischen Ankunft A und Abfahrt B.
So schaut es richtig gut aus, echt genial.

Vielen Dank dafür, auch für die Zeit, die Du mit mir investiert hast.

Grüße

Jürgen

**Comment by gaudes** [comment]
Hallo @juergenS09 ,

perfekt dass es nun klappt.

Ich mache das Issue hier zu und baue eine neue Version. Diese veröffentliche ich dann erstmal im Beta-Zweig und dann ca. 1-2 Wochen später im Default-Zweig.

Danke auch und bis dann ...

VG Ralf
